# Tensorflow Fundamentals

**Tensorflow is an end to end platform to perform machine learning and deep learning task that allows to find patterns in the data**. It helps to predict uncovered, hidden and new patterns in the data which can be used to decide future planning, strategies and actions.

**What we will be covering in this tutorial**

1. Tensorflow basics and fundamentals
2. Preprocessing data (getting it into tensors)
3. Building and using pre-trained deep learning models
4. Fitting a model to the data (to learn patterns)
5. Making prediction with a model (using patterns)
6. Evaluating model predictions
7. Saving and loading the models
8. Using trained model to make predictions on custom data

**What is covered in this file from coding perspective**
* Tensor introduction
* Getting information from tensors
* Manipulating Tensors
* Tensors and Numpy
* Using @tf function (method to speed up regular python functions)


## Exloring tf.constant() 

In [2]:
# import tensorflow
import tensorflow as tf
print(tf.__version__)

2.8.0


In [3]:
# Create tensor with tf.constant() of size 7
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
# Check the number of dimensions using ndim 
scalar.ndim

0

In [5]:
# Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
# Check vector dimension
vector.ndim

1

In [7]:
# Create matrix
matrix = tf.constant([ [10, 7], [7, 10] ])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [8]:
# Check matrix dimension
matrix.ndim

2

In [9]:
# Create another matrix and change the by default data type int32 to float16
another_matrix = tf.constant([[10., 7.],
                      [7., 10.],
                      [3., 7.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 7., 10.],
       [ 3.,  7.]], dtype=float16)>

In [10]:
# Observe dimension, it shows that total number of dimension in each shape
# shape is [3, 2] which shows how many elements are there in each shape 
another_matrix.ndim

2

In [11]:
# Let's create tensor
tensor = tf.constant([[[3, 2, 3],
                       [3, 2, 3]],
                      [[4, 5, 3],
                       [4, 6, 3]],
                      [[2, 2, 3],
                       [4, 4, 3]]
                       ])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[3, 2, 3],
        [3, 2, 3]],

       [[4, 5, 3],
        [4, 6, 3]],

       [[2, 2, 3],
        [4, 4, 3]]], dtype=int32)>

In [12]:
# Check dimension
tensor.ndim

3

In [13]:
# Let's create new tensor and understand
new_tensor = tf.constant([[[3, 2, 3],
                       [3, 2, 3]],
                      [[4, 5, 4],
                       [4, 6, 6]],
                      [[2, 2, 5],
                       [4, 4, 5]]
                       ])
new_tensor, new_tensor.ndim

(<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
 array([[[3, 2, 3],
         [3, 2, 3]],
 
        [[4, 5, 4],
         [4, 6, 6]],
 
        [[2, 2, 5],
         [4, 4, 5]]], dtype=int32)>, 3)

**What we have covered so far**
* Scalar: A single number
* Vector: A number with direction
* Matrix: A 2-dimensional array
* Tensor: An n-dimensional array (0-dim: scalar, 1-dim: vector)


## Exploring tf.Variable()

In [14]:
# Create same tensor as created above with tf.Variable()
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [15]:
# Changing array of changeable_tensor
changeable_tensor[0].assign(2)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([2, 7], dtype=int32)>

In [16]:
# Create single value variable
single_var = tf.Variable(1.5)
single_var

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.5>

In [17]:
# Change single value variable
single_var.assign(2.5)
single_var

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=2.5>

## Exploring random tensors

In [18]:
# Create two random generator 
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3, 2)) #Normal distribution

random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2)) #Normal distribution

# Are they equal?
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

## Shuffle tensors elements order

In [19]:
# Declaring tensor to Shuffle
not_shuffled_tensor = tf.constant([[10, 7], 
                      [6, 6],
                      [8, 10]])
not_shuffled_tensor, not_shuffled_tensor.ndim

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 6,  6],
        [ 8, 10]], dtype=int32)>, 2)

In [20]:
# Shuffling the tensor declared above
tf.random.shuffle(not_shuffled_tensor)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 8, 10],
       [ 6,  6],
       [10,  7]], dtype=int32)>

In [21]:
# Setting seed value in shuffling, it will shuffle differently in each execution
tf.random.shuffle(not_shuffled_tensor, seed=42) #operation level seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 8, 10],
       [ 6,  6],
       [10,  7]], dtype=int32)>

In [22]:
# Setting seed value in shuffling, shuffling must be same at each execution
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled_tensor, seed=42) 

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 6,  6],
       [ 8, 10]], dtype=int32)>

In [23]:
# Setting seed value in shuffling, shuffling must be same at each execution
tf.random.set_seed(42) # global level random seed
tf.random.shuffle(not_shuffled_tensor)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 6,  6],
       [ 8, 10],
       [10,  7]], dtype=int32)>

## Creating tensors using Numpy Arrays

In [24]:
# Create tensor of all ones
tf.ones(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [25]:
# Create tensor of all zeros
tf.zeros(shape=(3, 4)) 

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

The difference between tensors and numpy is that tensors can run much faster than numpy on GPU

In [26]:
import numpy as np
# Turn numpy arrays into tensors
numpy_A = np.arange(1, 25, dtype=np.int32) #numpy array between 1 to 25 of int
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [27]:
# Convert numpy_A to tensor
A = tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [28]:
# Convert numpy into n-dimension
B = tf.constant(numpy_A, shape=(2, 3, 4))
B, B.ndim

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>, 3)

In [29]:
# Convert numpy into n-dimension
C = tf.constant(numpy_A, shape=(3, 8))
C, C.ndim

(<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>, 2)

In [30]:
type(C[0]), C[0]

(tensorflow.python.framework.ops.EagerTensor,
 <tf.Tensor: shape=(8,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)>)

## Getting information from tensors


> **Shape**: The length (no. of elements) of each of the dimensions of a tensor

> **Rank**: The number of tensor dimension, a scalar has rank 0, a vector has rank 1, a matrix has rank 2, a tensor has rank n


> **Axis**: A particular dimension of a tensor e.g. tensor[0], tensor[:, 1]



> **Dimension**: The total number of items in the tensor e.g. tf.size(tensor)

In [31]:
# Create a rank 4 tensor
rank_4_tensor = tf.zeros(shape=(2, 3, 4, 5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [32]:
# Accessing tensor
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [33]:
# Get Tensor details
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [34]:
# Get various attributes of tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimension (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along the 0 axis:", rank_4_tensor.shape[0])
print("Elements along the last axis:", rank_4_tensor.shape[1])
print("Total number of elements in tensor:", tf.size(rank_4_tensor))
print("Total number of elements in tensor:", tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimension (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the last axis: 3
Total number of elements in tensor: tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in tensor: 120


## Indexing and Expanding Tensors
tensors can be indexed just like python lists

In [35]:
# Get first two elements of each dimension of tensor rank_4_tensor
rank_4_tensor[:2, :2, :2 , :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [36]:
# Get the first two elements of each dimension of tensor except last one
rank_4_tensor[:2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [37]:
# Create new tensor
rank_2_tensor = tf.constant([[10, 7],
                              [2, 3]])
rank_2_tensor.ndim

2

In [38]:
# Get the last item of each row from rank_2_tensor
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 3], dtype=int32)>

In [39]:
# Adding an extra dimension to rank_2_tensor 
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 2],
        [ 3]]], dtype=int32)>

In [40]:
# Another way to add an extra dimension to rank_2_tensor
another_rank_3_tensor = rank_2_tensor[:, :, tf.newaxis]
another_rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 2],
        [ 3]]], dtype=int32)>

In [41]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=0) # -1 means expand final axis,

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 2,  3]]], dtype=int32)>

## Manipulating Tensors

**Basic Arithmatic Operation**



In [42]:
# Get updated tensor by adding numbers to all elements
tensor = tf.constant([[10, 7], [3, 4]])
tensor + 10 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [43]:
# Orignial tensor value remain unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [44]:
# Original Tensor values changed
tensor = tensor + 10
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [45]:
tensor - 10 + 2 * 2 # Original tensor remains unchanged

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[14, 11],
       [ 7,  8]], dtype=int32)>

In [46]:
# Tensorflow in-built functions
tf.subtract(tensor, 2) #Original tensor remains unchanged


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[18, 15],
       [11, 12]], dtype=int32)>

In [47]:
tf.math.add(tensor, 2) #with or without .math method basic operations can be done

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[22, 19],
       [15, 16]], dtype=int32)>

In [48]:
print("Original Tensor:", tensor)
print("\nTensor Multiplication Subscript wise:")
tensor * tensor

Original Tensor: tf.Tensor(
[[20 17]
 [13 14]], shape=(2, 2), dtype=int32)

Tensor Multiplication Subscript wise:


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[400, 289],
       [169, 196]], dtype=int32)>

## Matrix Multiplication

In [49]:
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[621, 578],
       [442, 417]], dtype=int32)>

In [50]:
new_mul_tensor = tf.constant([[1,2,3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
new_mul_tensor

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [51]:
# reshape new_tensor
tf.reshape(new_mul_tensor, shape=(3, 4))

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]], dtype=int32)>

In [52]:
# Transpose the new_tensor while reshaping
tf.transpose(tf.reshape(new_mul_tensor, shape=(3, 4)))

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]], dtype=int32)>

## Changing data type of tensors
`By default tensor data type is integer`

In [53]:
tensor_A = tf.constant([10, 7])
tensor_A

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>

In [54]:
tensor_B = tf.constant([10.7, 7.10])
tensor_B

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([10.7,  7.1], dtype=float32)>

In [55]:
# Change data type from float32 to float16 (reduce precision)
tensor_C = tf.cast(tensor_B, dtype=tf.float16)
tensor_C.dtype

tf.float16

## Tensor Aggregation

In [56]:
D = tf.constant([-10, -7])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-10,  -7], dtype=int32)>

In [57]:
# Get absolute values of tensor
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>

In [58]:
# Create a random tensor with values between 0 to 100 of size 50
E = tf.constant(np.random.randint(0, 100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([48, 93, 20, 54, 22, 70, 43, 62,  7, 10, 61, 76, 10, 27, 33, 51, 34,
       48, 61, 73, 47, 36, 35, 53,  0, 66, 67, 91, 67, 74, 18, 89, 77, 28,
       99,  4, 82, 65, 87, 50, 45, 14, 17,  4, 67, 75, 32, 89,  9, 58])>

In [59]:
E.shape, E.ndim, tf.size(E)

(TensorShape([50]), 1, <tf.Tensor: shape=(), dtype=int32, numpy=50>)

In [60]:
# Find the min in tensor
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [61]:
# Find the max in tensor
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [62]:
# Find the mean in tensor
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=48>

In [63]:
# Find the sum in tensor
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2448>

In [64]:
import tensorflow_probability as tfp
# Find the variance in tensor
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=753>

In [65]:
#Find the variance of tensor
tf.math.reduce_variance(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=752.39844>

In [66]:
# Find the standard deviation in tensor
tf.math.reduce_std(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=27.429882>

## Find positional max/min

In [67]:
# Create a new tensor to find positional maximum and minimum
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [68]:
# Find the positional maximum, returns largest value position across tensor axis
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [69]:
# Get largest value across tensor axis
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [70]:
# Check for equality
F[tf.argmax(F)] == tf.reduce_max(F) 

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [71]:
# Find minimum position and its value
tf.argmin(F), F[tf.argmin(F)]

(<tf.Tensor: shape=(), dtype=int64, numpy=16>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>)

## Squeezing Tensor (removing all single dimensions)

In [75]:
# Create tensor
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 1, 50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [76]:
G.shape, G.ndim

(TensorShape([1, 1, 1, 1, 50]), 5)

In [77]:
# Removes dimensions of size 1 from the shape of a tensor.
G_squeezed = tf.squeeze(G)
G_squeezed 

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [79]:
G_squeezed.shape, G_squeezed.ndim

(TensorShape([50]), 1)

## One-Hot Encoding Tensor

In [88]:
# Creating temp list
temp_list = [0, 1, 2, 3]
temp_list

[0, 1, 2, 3]

In [89]:
# One Hot Encoding tensor
tf.one_hot(temp_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [90]:
# Add custom values in one-hot encoding
tf.one_hot(temp_list, depth=4, on_value="YES", off_value="NO")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'YES', b'NO', b'NO', b'NO'],
       [b'NO', b'YES', b'NO', b'NO'],
       [b'NO', b'NO', b'YES', b'NO'],
       [b'NO', b'NO', b'NO', b'YES']], dtype=object)>

## More tensor maths operations

In [91]:
# Create a new tensor
H = tf.range(1, 10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [93]:
# Get tensor square
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [96]:
# Get tensor square root
tf.sqrt(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [99]:
# Get tensor log
tf.math.log(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

## Tensor & Numpy

In [100]:
# Create tensor from numpy arrays
J = tf.constant(np.array([1, 2, 3]))
J

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([1, 2, 3])>

In [101]:
# Convert tensor to numpy
np.array(J), type(np.array(J))

(array([1, 2, 3]), numpy.ndarray)

In [102]:
# Convert tensor 'J' to numpy array
J.numpy(), type(J.numpy())

(array([1, 2, 3]), numpy.ndarray)

## Finding Access to GPUs

`Graphical Processing Unit (GPU), a specialized processor originally designed to accelerate graphics rendering. GPUs can process many pieces of data simultaneously, making them useful for machine learning, video editing, and gaming applications.`

In [2]:
# Check GPU is available in machine
import tensorflow as tf
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [4]:
# Check what type of GPU is this
# if you run it in colab, you might get Tesla T4 GPU
!nvidia-smi

Wed May 11 06:46:42 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   46C    P8    10W /  70W |      3MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------